# T03 "Запутанный путь" -- относительные пути и навигация по ФС.
FROM linux-ctf/base:latest

COPY setup.sh /opt/setup.sh
RUN chmod 0755 /opt/setup.sh

ENV START_DIR=/home/ctf/work
WORKDIR /home/ctf/work
